### ISSUE TITLE
[paella.plugins.BreaksPlayerPlugin] Error checking breaks with trimmed videos

### ISSUE THREAD

**Issue by rubenrua** [polimediaupv/paella#229]
Steps to Reproduce: Add a break and a start timming into a video; the break doesn't work.

There is a difference between Paella4 and Paella5 when a video is trimmed. In Paella4 the current time of the time update event is the real value, in Paella5 the time has been corrected.

I don't know what is the correct behavior, use the real time or use the corrected one. Please let me know which one is the correct, to make a pull request with the fix.

**Comment by turro** [comment]
Fixed in develop in commit 846762f . Nov currentTime() has a ignoreTrimming parameter to allow this (default= false)

**Comment by miesgre** [comment]
@rubenrua Is this Issue solved?

**Comment by rubenrua** [comment]
I think it is not solved. :(



[`time.currentTime`](https://github.com/polimediaupv/paella/blob/develop/plugins/es.upv.paella.captionsPlugin/overlayCaptionsPlugin.js#L100) is not the real time needed for the captions.

**Comment by miesgre** [comment]
but, this issue is about paella.plugins.BreaksPlayerPlugin plugin, not for the captions plugin.

**Comment by iriadp** [comment]
I created another one because the cursor jumps to the absolute break end time, not the relative one to the trimmed beginning: https://github.com/polimediaupv/paella/issues/257

**Comment by ferserc1** [comment]
This is a brief explanation about breaks plugin, because I think that there are some confusion about it.

The breaks have nothing to do with the trimming because they have always worked using absolute time (ignoring trimming). If you set the breaks using trimmed values, you may need to modify the breaks if you change the trimming.
